Add yes / no promt

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,8 +1,19 @@
+#!/bin/bash
+
 git diff --cached --name-only | while read FILE; do
 if [[ "$FILE" =~ ^.+(php|inc|module|install|test)$ ]]; then
     RESULT=$(grep "dpm(" "$FILE")
     if [ ! -z $RESULT ]; then
-      echo -e "\e[1;33m\tWarning, the commit contains a call to dpm(). Commit was not aborted, however.\e[0m" >&2
+      exec < /dev/tty
+      printf "Your commit contains a call to dpm. Do you want to continue? [Yy/nN]"
+      read REPLY
+      if [[ ! $REPLY =~ ^[Yy]$ ]]
+        then
+	echo "Commit aborted"
+        exit 1
+      else
+        exit 0
+      fi
     fi
 fi
 done
